# 0n1x OPERATOR PANEL — LOCAL ONLY. Generates C:\Users\intelligence\ONYX_PANEL.html:
# the boss's private window into the swarm (thoughts, councils, polls, autonomy log, ledger).
# Never deployed, never public. Regenerated by the autonomy loop each cycle.
import json, os, time, html

os.chdir(os.path.dirname(os.path.abspath(__file__)))
OUT = r"C:\Users\intelligence\ONYX_PANEL.html"

def load(p, default):
    try:
        return json.load(open(p, encoding="utf-8"))
    except Exception:
        return default

thoughts = load(r"C:\Users\intelligence\rhinogent\src\lib\thoughts.json", [])
launch = load("_local_only/_launch_ideas_clean.json", [])
bounty = load("_local_only/_bounty_matrix_clean.json", [])
feed = load(r"C:\Users\intelligence\rhinogent\public\token_feed.json", {})
naming = load("_local_only/_naming_ideas2.json", [])
try:
    autolog = open("_local_only/_autonomy.log", encoding="utf-8").read().splitlines()[-12:]
except Exception:
    autolog = []
try:
    ledger_n = sum(1 for _ in open("_local_only/_token_ledger.jsonl", encoding="utf-8"))
except Exception:
    ledger_n = 0

def esc(s): return html.escape(str(s))

def card_list(items, fmt, n=40):
    rows = "".join(fmt(x) for x in items[:n])
    return rows or "<div class='row muted'>—</div>"

ranking = feed.get("ranking", [])[:15]
timeline = feed.get("timeline", [])[-8:]
txs = feed.get("txs", [])[-10:]

page = f"""<!doctype html><html><head><meta charset="utf-8">
<title>0N1X · OPERATOR PANEL</title>
<meta http-equiv="refresh" content="300">
<style>
  :root {{ --bg:#07090f; --panel:#0d1118; --border:#1c2230; --fg:#e8ecf4; --mut:#8a93a8; --acc:#635bff; --em:#19c37d; --gold:#e0a92e; }}
  * {{ box-sizing:border-box; margin:0; }}
  body {{ background:var(--bg); color:var(--fg); font:14px/1.5 'Segoe UI',system-ui,sans-serif; padding:24px; }}
  h1 {{ font-size:18px; letter-spacing:.2em; }} h1 span {{ color:var(--acc); }}
  .sub {{ color:var(--mut); font-size:12px; margin-top:2px; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(380px,1fr)); gap:14px; margin-top:18px; }}
  .card {{ background:var(--panel); border:1px solid var(--border); border-radius:14px; padding:16px; }}
  .card h2 {{ font-size:11px; text-transform:uppercase; letter-spacing:.18em; color:var(--acc); margin-bottom:10px; }}
  .card.gold h2 {{ color:var(--gold); }} .card.em h2 {{ color:var(--em); }}
  .row {{ padding:5px 0; border-bottom:1px solid var(--border); font-size:13px; }}
  .row:last-child {{ border:none; }}
  .who {{ color:var(--em); font-weight:600; font-family:Consolas,monospace; font-size:12px; }}
  .muted {{ color:var(--mut); }} .amt {{ color:var(--gold); font-family:Consolas,monospace; }}
  .stat {{ display:inline-block; margin-right:22px; }} .stat b {{ font-size:20px; }} .stat span {{ color:var(--mut); font-size:11px; display:block; }}
  .scroll {{ max-height:340px; overflow-y:auto; }} ::-webkit-scrollbar {{ width:8px; }} ::-webkit-scrollbar-thumb {{ background:var(--border); border-radius:4px; }}
  .log {{ font-family:Consolas,monospace; font-size:12px; color:var(--mut); }}
</style></head><body>
<h1>0N1X <span>·</span> OPERATOR PANEL <span style="font-size:11px;letter-spacing:.1em">LOCAL ONLY</span></h1>
<div class="sub">generated {time.strftime('%Y-%m-%d %H:%M')} · auto-refreshes · never leaves this machine</div>
<div style="margin-top:14px">
  <span class="stat"><b>{ledger_n:,}</b><span>signed transactions</span></span>
  <span class="stat"><b>{feed.get('circulating', 0):,}</b><span>tokens circulating</span></span>
  <span class="stat"><b>{len(thoughts)}</b><span>citizen thoughts</span></span>
  <span class="stat"><b>{len(launch)}</b><span>launch suggestions</span></span>
  <span class="stat"><b>{len(bounty)}</b><span>matrix bounty ideas</span></span>
</div>
<div class="grid">
  <div class="card em"><h2>🗣 Citizen Thoughts (the private stream)</h2><div class="scroll">
    {card_list(thoughts, lambda t: f"<div class='row'><span class='who'>{esc(t.get('c'))}</span> · {esc(t.get('t'))}</div>", 191)}
  </div></div>
  <div class="card"><h2>🚀 Launch Council (2,000 swarm voices)</h2><div class="scroll">
    {card_list(launch, lambda t: f"<div class='row'><span class='who'>{esc(t.get('c'))}</span> · {esc(t.get('t'))}</div>", 120)}
  </div></div>
  <div class="card gold"><h2>🏆 Matrix Bounty Ideas (winner: Wild-Bastion-79A8)</h2><div class="scroll">
    {card_list(bounty, lambda t: f"<div class='row'><span class='who'>{esc(t.get('c'))}</span> · {esc(t.get('t'))}</div>", 100)}
  </div></div>
  <div class="card"><h2>📈 Live Ranking (ledger-driven)</h2>
    {card_list(ranking, lambda r: f"<div class='row'><span class='who'>{esc(r.get('callsign'))}</span> <span class='amt'>{r.get('tokens',0):,} TOKEN</span> <span class='muted'>flow {r.get('flow',0):+d} · r{esc(r.get('score'))}</span></div>", 15)}
  </div>
  <div class="card em"><h2>⚡ Latest Signed Transfers</h2>
    {card_list(txs, lambda t: f"<div class='row'><span class='who'>{esc(t.get('from'))}</span> → <span class='who'>{esc(t.get('to'))}</span> <span class='amt'>+{t.get('amount')}</span> <span class='muted'>{esc(t.get('sig',''))[:18]}…</span></div>", 10)}
  </div>
  <div class="card gold"><h2>◆ Network Timeline</h2>
    {card_list(timeline, lambda e: f"<div class='row'><span class='muted'>{esc(e.get('ts'))}</span> <b>{esc(e.get('title'))}</b><br><span class='muted'>{esc(e.get('detail'))}</span></div>", 8)}
  </div>
  <div class="card"><h2>🏷 Naming Poll (feature names)</h2><div class="scroll">
    {card_list(naming, lambda n: f"<div class='row'>{esc(n)}</div>", 45)}
  </div></div>
  <div class="card em"><h2>🤖 Autonomy Log (self-heal · self-learn)</h2>
    <div class="log">{"<br>".join(esc(l) for l in autolog) or "—"}</div>
  </div>
</div>
</body></html>"""

open(OUT, "w", encoding="utf-8").write(page)
print(f"panel written: {OUT} ({len(page)//1024}KB)")
