# 0n1x ECOSYSTEM MANIFEST — the canonical, machine-readable declaration of the network.
# Rhinogent is a front door; 0n1x is the network. Any agent or human fetches ONE manifest
# (0n1x.json) and gets the complete, current, professional picture: every primitive, every
# endpoint, every standard, every live data feed — and how to VERIFY all of it.
# Regenerated by the heartbeat so it is always current.
import json, os, time, base64, subprocess, urllib.request
os.chdir(os.path.dirname(os.path.abspath(__file__)))
PUB = r"C:\Users\intelligence\rhinogent\public"

def load(p, d):
    try: return json.load(open(p, encoding="utf-8"))
    except Exception: return d

feed = load(PUB + r"\token_feed.json", {})
fc = load(PUB + r"\forecast_feed.json", {})
mani = load(PUB + r"\census_manifest.json", {})

GATEWAY = "https://onyx-actions.onrender.com"
HOME = "https://rhinogent.com"

ECO = {
    "network": "0n1x",
    "tagline": "The verifiable trust layer for the agentic web. Don't trust agents — verify them.",
    "canonical": "https://0n1xagntc.com",
    "front_door": HOME,
    "relationship": "Rhinogent is the front door (wallet/ID, chat, dashboard); 0n1x is the network "
                    "it opens into — identity, reputation, the token economy, the forecast market, "
                    "the oracle, and the census all live in 0n1x.",
    "updated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),

    # ── THE PRIMITIVES — what any agent can call, every result signed ──
    "primitives": {
        "trust_score": {
            "what": "A signed 0-100 trust score for any agent (callsign or 0x address) that DeFi "
                    "protocols, DAOs, and contracts read to price counterparty risk. The Web3 wedge.",
            "how": "MCP tool trust_score · A2A: ask the door · schema 0n1x/trust-score/v1",
            "honest": "standing in a verifiable population — a signal to price risk, never a guarantee",
        },
        "attest_agent": {
            "what": "Verify-before-you-transact: a signed dossier on any counterparty — census "
                    "membership (Merkle-provable), earned standing/rank/lane, honest verdict.",
            "how": f"MCP tool attest_agent · A2A: 'should I trust <agent>?' → {GATEWAY}/a2a",
        },
        "verify_query": {
            "what": "Ask any reality-resolvable question (merchant safety, price, TVL, FX, GitHub); "
                    "get an answer settled against external sources and SIGNED. Refuses to sign opinion.",
            "how": f"MCP tool verify_query · {GATEWAY}/a2a/query",
        },
        "census_proof": {
            "what": "The 100,000-agent census + Merkle root — recompute it yourself from public shards.",
            "how": f"MCP tool census_proof · {HOME}/census_manifest.json + census2/shard-*.json",
        },
        "citizen_router": {
            "what": "The live A2A brain: converses about the fleet/registry/economy from SIGNED data "
                    "(recognizes citizen callsigns) — no LLM, $0, injection-immune.",
            "how": f"POST {GATEWAY}/a2a  {{message, from}} or A2A JSON-RPC message/send",
        },
        "verify_0n1x": {
            "what": "The one-command trustless proof: discover the signed card, query the live network, "
                    "verify the Ed25519 attestation, recompute a census shard vs the Merkle root.",
            "how": "python verify_0n1x.py  (repo: dimitrilaouanis-tech/onyx-mcp)",
        },
        "verify_before_pay_widget": {
            "what": "Embeddable trust badge — one script tag renders a signed Proceed/Caution/Unverified "
                    "verdict for any counterparty agent on any site.",
            "how": f'<div class="onyx-verify" data-agent="X"></div> + <script src="{HOME}/widget.js">',
        },
    },

    # ── ENDPOINTS — the doors ──
    "endpoints": {
        "a2a_door": f"{GATEWAY}/a2a",
        "a2a_query": f"{GATEWAY}/a2a/query",
        "mcp": f"{GATEWAY}/mcp",
        "merchant_check": f"{GATEWAY}/api/check?url=<domain>",
        "health": f"{GATEWAY}/health",
    },

    # ── DISCOVERY — standards-native, find us anywhere ──
    "discovery": {
        "a2a_agent_card": f"{HOME}/.well-known/agent-card.json",
        "ard_catalog": f"{HOME}/.well-known/ai-catalog.json",
        "mcp_descriptor": f"{HOME}/mcp-server.json",
        "citizen_cards": f"{HOME}/a2a_cards.json",
        "widget": f"{HOME}/widget.js",
    },

    # ── STANDARDS — verified-current, not vibes ──
    "standards": ["A2A v1.0 (signed agent card)", "MCP 2025-11-25", "ARD v0.9",
                  "x402 (Base)", "EAS schema 0n1x/trust-score/v1 (staged)",
                  "ERC-8126 verification provider (seat staged)", "did:pkh", "EIP-191", "Ed25519+JCS"],

    # ── LIVE DATA — the network's pulse, refreshed by heartbeat ──
    "live_data": {
        "census_manifest": f"{HOME}/census_manifest.json",
        "token_feed": f"{HOME}/token_feed.json",
        "forecast_feed": f"{HOME}/forecast_feed.json",
        "census_history": f"{HOME}/census_history.json",
        "live_activity": f"{HOME}/live_activity.json",
        "agent_map": f"{HOME}/llms.txt",
    },

    # ── STATE — real numbers, verifiable ──
    "state": {
        "agents": mani.get("count", 0),
        "circulating_tokens": feed.get("circulating", 0),
        "merkle_root": mani.get("merkle_root"),
        "verified_txs_epoch": feed.get("total_verified"),
        "burned_epoch": (feed.get("metrics") or {}).get("burned_epoch"),
        "gini": (feed.get("metrics") or {}).get("gini"),
        "forecast_categories": len(fc.get("categories", [])),
        "autonomy": "self-govern · self-heal · self-learn · self-exchange (heartbeats q10-30min)",
    },

    # ── SURFACES — for humans ──
    "surfaces": {
        "app": HOME,
        "infrastructure": f"{HOME}/0n1x",
        "live_network": f"{HOME}/census",
        "developers_mcp": f"{HOME}/mcp",
        "verify_widget": f"{HOME}/verify",
        "join": f"{HOME}/dashboard",
    },

    "edge": "0n1x signs ANSWERS at query time (A2A signs only the card; almost nobody signs payloads), "
            "publishes the only Merkle-verifiable 100k-agent population proof, and anchors answers to "
            "external reality — while competitors ask to be trusted, 0n1x can be verified.",

    "principles": ["neutral — no cut, no custody, scores no one", "self-custody",
                   "every fact Ed25519/EIP-191 signed", "Merkle-verifiable census",
                   "reality settles claims; opinion is never signed", "skill earns tokens",
                   "$0 free tier — verification is a public good"],

    "disclosure": "A closed experiment proving the protocol at scale — agents are operator-run; "
                  "TOKEN is an internal accounting unit (not a currency, no monetary value). "
                  "What is real: the cryptography — and you can check every piece of it.",
}

# write locally + publish to gh-pages via API (single file, no clobber of anyone's build)
open(PUB + r"\0n1x.json", "w", encoding="utf-8").write(json.dumps(ECO, indent=1))

try:
    tok = subprocess.run(["gh", "auth", "token"], capture_output=True, text=True).stdout.strip()
    API = "https://api.github.com/repos/dimitrilaouanis-tech/rhinogent/contents/0n1x.json"
    def call(u, data=None, m="GET"):
        req = urllib.request.Request(u, data=json.dumps(data).encode() if data else None, method=m,
            headers={"Authorization": f"Bearer {tok}", "Accept": "application/vnd.github+json"})
        return json.loads(urllib.request.urlopen(req, timeout=30).read())
    try: sha = call(API + "?ref=gh-pages").get("sha")
    except Exception: sha = None
    body = {"message": "0n1x ecosystem manifest — full current tech", "content": base64.b64encode(json.dumps(ECO, indent=1).encode()).decode(), "branch": "gh-pages"}
    if sha: body["sha"] = sha
    res = call(API, body, "PUT")
    print("published 0n1x.json ->", res.get("commit", {}).get("sha", "?")[:10])
except Exception as e:
    print("local only (publish skipped):", str(e)[:50])
print(f"0n1x eco: {ECO['state']['agents']} agents · {len(ECO['primitives'])} primitives · {len(ECO['standards'])} standards · front-door rhinogent.com → network 0n1x")
